name: tpm2
version: 1.0-6-dev
summary: TPM 2.0 utilities
description: |
  Set of utilities and a daemon to deal with TPM 2.0 chips built
  into a wide range of todays devices. Please find the source
  code at: https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/tpm2
confinement: strict
grade: stable

# NOTE: the alias syntax is depreciated with snapd 2.25 however it needs to
# stay to guarantee that all clients are updated correctly.

slots:
  tcti-dbus-server-side:
    interface: dbus
    name: com.intel.tss2.Tabrmd
    bus: system

plugs:
  tcti-dbus-app-side:
    interface: dbus
    name: com.intel.tss2.Tabrmd
    bus: system

apps:
  resourcemgr:
    command: sbin/tpm2-abrmd
    slots: [tcti-dbus-server-side]
    plugs: [tpm, network]
    aliases: [tpm2-abrmd, resourcemgr]
  activatecredential:
    command: sbin/tpm2_activatecredential
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_activatecredential]
  akparse:
    command: sbin/tpm2_akparse
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_akparse]
  certify:
    command: sbin/tpm2_certify
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_certify]
  create:
    command: sbin/tpm2_create
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_create]
  createprimary:
    command: sbin/tpm2_createprimary
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_createprimary]
  encryptdecrypt:
    command: sbin/tpm2_encryptdecrypt
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_encryptdecrypt]
  evictcontrol:
    command: sbin/tpm2_evictcontrol
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_evictcontrol]
  getmanufec:
    command: sbin/tpm2_getmanufec
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_getmanufec]
  getpubak:
    command: sbin/tpm2_getpubak
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_getpubak]
  getpubek:
    command: sbin/tpm2_getpubek
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_getpubek]
  getrandom:
    command: sbin/tpm2_getrandom
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_getrandom]
  hash:
    command: sbin/tpm2_hash
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_hash]
  hmac:
    command: sbin/tpm2_hmac
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_hmac]
  listpcrs:
    command: sbin/tpm2_listpcrs
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_listpcrs]
  load:
    command: sbin/tpm2_load
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_load]
  loadexternal:
    command: sbin/tpm2_loadexternal
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_loadexternal]
  makecredential:
    command: sbin/tpm2_makecredential
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_makecredential]
  nvdefine:
    command: sbin/tpm2_nvdefine
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_nvdefine]
  nvlist:
    command: sbin/tpm2_nvlist
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_nvlist]
  nvread:
    command: sbin/tpm2_nvread
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_nvread]
  nvrelease:
    command: sbin/tpm2_nvrelease
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_nvrelease]
  nvwrite:
    command: sbin/tpm2_nvwrite
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_nvwrite]
  quote:
    command: sbin/tpm2_quote
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_quote]
  rc-decode:
    command: sbin/tpm2_rc_decode
    aliases: [tpm2_rc_decode]
  readpublic:
    command: sbin/tpm2_readpublic
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_readpublic]
  rsadecrypt:
    command: sbin/tpm2_rsadecrypt
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_rsadecrypt]
  rsaencrypt:
    command: sbin/tpm2_rsaencrypt
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_rsaencrypt]
  sign:
    command: sbin/tpm2_sign
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_sign]
  takeownership:
    command: sbin/tpm2_takeownership
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_takeownership]
  unseal:
    command: sbin/tpm2_unseal
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_unseal]
  verifysignature:
    command: sbin/tpm2_verifysignature
    plugs: [tcti-dbus-app-side, network, home]
    aliases: [tpm2_verifysignature]

parts:
  common:
    plugin: dump
    source: .
    prime:
      - copyright.tpm2-tss
      - copyright.tpm2-tools

  tpm2-tss:
    plugin: autotools
    # You can download the latest official release from:
    # https://github.com/tpm2-software/tpm2-tss/releases/latest
    source: https://github.com/tpm2-software/tpm2-tss/releases/download/1.4.0/tpm2-tss-1.4.0.tar.gz
    source-checksum: sha256/cf8784cc536be16e6fba47f77033e093a6aeaed8420877ac9f42f77fb7b09031
    configflags:
      - --disable-static
      - --enable-unit
    build-packages:
      - libtool
      - gcc
      - g++
      - libc6-dev
      - libcmocka-dev
    prime:
      - -include
      - -lib/pkgconfig

  tpm2-abrmd:
    # You can download the latest official release from:
    # https://github.com/intel/tpm2-abrmd/releases/latest
    source: https://github.com/intel/tpm2-abrmd/releases/download/1.2.0/tpm2-abrmd-1.2.0.tar.gz
    source-checksum: sha256/e20d2796c3097f9eec8410cec6a99d1532769d1cc138d6d9331c8ee1f0d305a4
    after:
      - tpm2-tss
    plugin: autotools
    configflags:
      - --disable-static
      - --enable-unit
      - "CFLAGS=-Wno-int-to-pointer-cast"
    build-packages:
      - libc6-dev
      - libcmocka-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libtool
      - pkg-config
    prime:
      - -include
      - -lib/pkgconfig
    install: |
      # Run all tests shipped by default
      make check

  tpm2-tools:
    plugin: autotools
    #
    # By default the snapcraft autotools plugin doesn't
    # specify the -O2 CFLAG when compiling C/C++.  This
    # causes an undefined symbol when building tpm2_nvlist.
    configflags:
      - "CFLAGS=-O2"
    source: https://github.com/intel/tpm2-tools.git
    source-type: git
    source-branch: 2.X
    configflags:
      - --with-tcti-tabrmd
      - --enable-unit
    build-packages:
      - autoconf
      - autoconf-archive
      - pkg-config
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
    prime:
      - -include
    after:
      - tpm2-tss
      - tpm2-abrmd
    install: |
      # Run all tests shipped by default
      make check

  tpm2-pk11:
    after:
      - tpm2-tss
      - tpm2-abrmd
    source: https://github.com/irtimmer/tpm2-pk11.git
    source-type: git
    plugin: cmake
    build-packages:
      - libp11-kit-dev
      - libtasn1-dev
