name: tpm2
version: 1.0-6-dev
summary: TPM 2.0 utilities
description: |
  Set of utilities and a daemon to deal with TPM 2.0 chips built
  into a wide range of todays devices. Please find the source
  code at: https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/tpm2
confinement: strict
grade: stable

# NOTE: the alias syntax is depreciated with snapd 2.25 however it needs to
# stay to guarantee that all clients are updated correctly.

apps:
  resourcemgr:
    command: sbin/resourcemgr
    daemon: simple
    plugs: [tpm, network-bind]
  activatecredential:
    command: sbin/tpm2_activatecredential
    plugs: [network, home]
    aliases: [tpm2_activatecredential]
  akparse:
    command: sbin/tpm2_akparse
    plugs: [network, home]
    aliases: [tpm2_akparse]
  certify:
    command: sbin/tpm2_certify
    plugs: [network, home]
    aliases: [tpm2_certify]
  create:
    command: sbin/tpm2_create
    plugs: [network, home]
    aliases: [tpm2_create]
  createprimary:
    command: sbin/tpm2_createprimary
    plugs: [network, home]
    aliases: [tpm2_createprimary]
  encryptdecrypt:
    command: sbin/tpm2_encryptdecrypt
    plugs: [network, home]
    aliases: [tpm2_encryptdecrypt]
  evictcontrol:
    command: sbin/tpm2_evictcontrol
    plugs: [network, home]
    aliases: [tpm2_evictcontrol]
  getmanufec:
    command: sbin/tpm2_getmanufec
    plugs: [network, home]
    aliases: [tpm2_getmanufec]
  getpubak:
    command: sbin/tpm2_getpubak
    plugs: [network, home]
    aliases: [tpm2_getpubak]
  getpubek:
    command: sbin/tpm2_getpubek
    plugs: [network, home]
    aliases: [tpm2_getpubek]
  getrandom:
    command: sbin/tpm2_getrandom
    plugs: [network, home]
    aliases: [tpm2_getrandom]
  hash:
    command: sbin/tpm2_hash
    plugs: [network, home]
    aliases: [tpm2_hash]
  hmac:
    command: sbin/tpm2_hmac
    plugs: [network, home]
    aliases: [tpm2_hmac]
  listpcrs:
    command: sbin/tpm2_listpcrs
    plugs: [network, home]
    aliases: [tpm2_listpcrs]
  load:
    command: sbin/tpm2_load
    plugs: [network, home]
    aliases: [tpm2_load]
  loadexternal:
    command: sbin/tpm2_loadexternal
    plugs: [network, home]
    aliases: [tpm2_loadexternal]
  makecredential:
    command: sbin/tpm2_makecredential
    plugs: [network, home]
    aliases: [tpm2_makecredential]
  nvdefine:
    command: sbin/tpm2_nvdefine
    plugs: [network, home]
    aliases: [tpm2_nvdefine]
  nvlist:
    command: sbin/tpm2_nvlist
    plugs: [network, home]
    aliases: [tpm2_nvlist]
  nvread:
    command: sbin/tpm2_nvread
    plugs: [network, home]
    aliases: [tpm2_nvread]
  nvrelease:
    command: sbin/tpm2_nvrelease
    plugs: [network, home]
    aliases: [tpm2_nvrelease]
  nvwrite:
    command: sbin/tpm2_nvwrite
    plugs: [network, home]
    aliases: [tpm2_nvwrite]
  quote:
    command: sbin/tpm2_quote
    plugs: [network, home]
    aliases: [tpm2_quote]
  rc-decode:
    command: sbin/tpm2_rc_decode
    aliases: [tpm2_rc_decode]
  readpublic:
    command: sbin/tpm2_readpublic
    plugs: [network, home]
    aliases: [tpm2_readpublic]
  rsadecrypt:
    command: sbin/tpm2_rsadecrypt
    plugs: [network, home]
    aliases: [tpm2_rsadecrypt]
  rsaencrypt:
    command: sbin/tpm2_rsaencrypt
    plugs: [network, home]
    aliases: [tpm2_rsaencrypt]
  sign:
    command: sbin/tpm2_sign
    plugs: [network, home]
    aliases: [tpm2_sign]
  takeownership:
    command: sbin/tpm2_takeownership
    plugs: [network, home]
    aliases: [tpm2_takeownership]
  unseal:
    command: sbin/tpm2_unseal
    plugs: [network, home]
    aliases: [tpm2_unseal]
  verifysignature:
    command: sbin/tpm2_verifysignature
    plugs: [network, home]
    aliases: [tpm2_verifysignature]

parts:
  common:
    plugin: dump
    source: .
    prime:
      - copyright.tpm2-tss
      - copyright.tpm2-tools

  tpm2-tss:
    plugin: autotools
    # You can download the latest official release from:
    # https://github.com/intel/tpm2-tss/releases/latest
    source: https://github.com/intel/tpm2-tss/releases/download/1.3.0/tpm2-tss-1.3.0.tar.gz
    source-checksum: sha256/c7d627de50394e9a02593edb1ce74e1bbac17831be726c54f689507f0c41a78a
    configflags:
      - --enable-unit
    build-packages:
      - libtool
      - gcc
      - g++
      - libc6-dev
      - libcmocka-dev
    prime:
      - -include

  tpm2-tabrmd:
    # You can download the latest official release from:
    # https://github.com/intel/tpm2-abrmd/releases/latest
    source: https://github.com/intel/tpm2-abrmd/releases/download/1.2.0/tpm2-abrmd-1.2.0.tar.gz
    source-checksum: sha256/3f5d1d3fa3077a0a187cd13b87bab3916e411fdbe37a0ceb170249017cccd52c
    after:
      - tpm2-tss
    plugin: autotools
    configflags:
      - --enable-unit
      - "CFLAGS=-Wno-int-to-pointer-cast"
    build-packages:
      - libc6-dev
      - libcmocka-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libtool
      - pkg-config
    install: |
      # Run all tests shipped by default
      make check

  tpm2-tools:
    plugin: autotools
    #
    # By default the snapcraft autotools plugin doesn't
    # specify the -O2 CFLAG when compiling C/C++.  This
    # causes an undefined symbol when building tpm2_nvlist.
    configflags:
      - "CFLAGS=-O2"
    source: https://github.com/intel/tpm2-tools.git
    source-type: git
    source-branch: 2.X
    configflags:
      - --enable-unit
    build-packages:
      - autoconf
      - autoconf-archive
      - pkg-config
      - libcmocka-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libtool
    prime:
      - -include
    after:
      - tpm2-tss
    install: |
      # Run all tests shipped by default
      make check
